package com.lawyer.entity;

// Generated Aug 7, 2013 11:09:49 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Lawyer generated by hbm2java
 */
@Entity
@Table(name = "lawyer")
public class Lawyer implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int lawyerId;
	private String email;
	private String password;
	private String name;
	private String address;
	private Integer state;
	private String education;
	private String experience;
	private byte[] photo;
	private Set<PracticeArea> practiceAreas = new HashSet<PracticeArea>(0);
	private Set<ServiceFees> serviceFeeses = new HashSet<ServiceFees>(0);

	public Lawyer() {
	}

	public Lawyer(int lawyerId) {
		this.lawyerId = lawyerId;
	}

	public Lawyer(int lawyerId, String email, String password, String name,
			String address, Integer state, String education, String experience,
			byte[] photo, Set<PracticeArea> practiceAreas, 
			Set<ServiceFees> serviceFeeses) {
		this.lawyerId = lawyerId;
		this.email = email;
		this.password = password;
		this.name = name;
		this.address = address;
		this.state = state;
		this.education = education;
		this.experience = experience;
		this.photo = photo;
		this.practiceAreas = practiceAreas;
		
		this.serviceFeeses = serviceFeeses;
	}

	@Id
	@Column(name = "lawyer_id", unique = true, nullable = false)
	public int getLawyerId() {
		return this.lawyerId;
	}

	public void setLawyerId(int lawyerId) {
		this.lawyerId = lawyerId;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address", length = 65535)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "state")
	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	@Column(name = "education", length = 65535)
	public String getEducation() {
		return this.education;
	}

	public void setEducation(String education) {
		this.education = education;
	}

	@Column(name = "experience", length = 10)
	public String getExperience() {
		return this.experience;
	}

	public void setExperience(String experience) {
		this.experience = experience;
	}

	@Column(name = "photo")
	public byte[] getPhoto() {
		return this.photo;
	}

	public void setPhoto(byte[] photo) {
		this.photo = photo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lawyer")
	public Set<PracticeArea> getPracticeAreas() {
		return this.practiceAreas;
	}

	public void setPracticeAreas(Set<PracticeArea> practiceAreas) {
		this.practiceAreas = practiceAreas;
	}



	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lawyer")
	public Set<ServiceFees> getServiceFeeses() {
		return this.serviceFeeses;
	}

	public void setServiceFeeses(Set<ServiceFees> serviceFeeses) {
		this.serviceFeeses = serviceFeeses;
	}

}
