package com.lawyer.entity;

// Generated Aug 7, 2013 11:09:49 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Lawyer generated by hbm2java
 */
@Entity
@Table(name = "lawyer")
@NamedQueries({
@NamedQuery(name="Lawyer.findLawyerById",query="Select u FROM Lawyer u where u.lawyerId = :id"),
@NamedQuery(name="Lawyer.findAllLawyers",query="select u FROM Lawyer u")})
public class Lawyer implements java.io.Serializable {

	
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private int lawyerId;
	@Column
	private String specialization;
	
	@Column
	private String fullname;
	@Column(columnDefinition="text")
	private String aboutself;
	@Column
	private String address;
	@Column
	private String phonenumber;
	@Column
	private String email;
	
	public Lawyer()
	{}
	
	public Lawyer(String fullname, String aboutself, String address,
			String phonenumber, String email,String specialization) {
		super();
		this.fullname = fullname;
		this.aboutself = aboutself;
		this.address = address;
		this.phonenumber = phonenumber;
		this.email = email;
		this.specialization = specialization;
	}
	
	public int getLawyerId() {
		return lawyerId;
	}

	public void setLawyerId(int lawyerId) {
		this.lawyerId = lawyerId;
	}

	public String getSpecialization() {
		return specialization;
	}

	public void setSpecialization(String specialization) {
		this.specialization = specialization;
	}
	
	public String getFullname() {
		return fullname;
	}
	public void setFullname(String fullname) {
		this.fullname = fullname;
	}
	public String getAboutself() {
		return aboutself;
	}
	public void setAboutself(String aboutself) {
		this.aboutself = aboutself;
	}
	public String getAddress() {
		return address;
	}
	public void setAddress(String address) {
		this.address = address;
	}
	public String getPhonenumber() {
		return phonenumber;
	}
	public void setPhonenumber(String phonenumber) {
		this.phonenumber = phonenumber;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	

}
