package com.lawyer.entity;

// Generated Aug 7, 2013 11:09:49 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PracticeArea generated by hbm2java
 */
@Entity
@Table(name = "practice_area")
public class PracticeArea implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private PracticeAreaId id;
	private Lawyer lawyer;

	public PracticeArea() {
	}

	public PracticeArea(PracticeAreaId id, Lawyer lawyer) {
		this.id = id;
		this.lawyer = lawyer;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "lawyerId", column = @Column(name = "lawyer_id", nullable = false)),
			@AttributeOverride(name = "practiceArea", column = @Column(name = "practice_area", nullable = false, length = 20)) })
	public PracticeAreaId getId() {
		return this.id;
	}

	public void setId(PracticeAreaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "lawyer_id", nullable = false, insertable = false, updatable = false)
	public Lawyer getLawyer() {
		return this.lawyer;
	}

	public void setLawyer(Lawyer lawyer) {
		this.lawyer = lawyer;
	}

}
