package com.lawyer.entity;

// Generated Aug 7, 2013 11:09:49 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PracticeAreaId generated by hbm2java
 */
@Embeddable
public class PracticeAreaId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int lawyerId;
	private String practiceArea;

	public PracticeAreaId() {
	}

	public PracticeAreaId(int lawyerId, String practiceArea) {
		this.lawyerId = lawyerId;
		this.practiceArea = practiceArea;
	}

	@Column(name = "lawyer_id", nullable = false)
	public int getLawyerId() {
		return this.lawyerId;
	}

	public void setLawyerId(int lawyerId) {
		this.lawyerId = lawyerId;
	}

	@Column(name = "practice_area", nullable = false, length = 20)
	public String getPracticeArea() {
		return this.practiceArea;
	}

	public void setPracticeArea(String practiceArea) {
		this.practiceArea = practiceArea;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PracticeAreaId))
			return false;
		PracticeAreaId castOther = (PracticeAreaId) other;

		return (this.getLawyerId() == castOther.getLawyerId())
				&& ((this.getPracticeArea() == castOther.getPracticeArea()) || (this
						.getPracticeArea() != null
						&& castOther.getPracticeArea() != null && this
						.getPracticeArea().equals(castOther.getPracticeArea())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getLawyerId();
		result = 37
				* result
				+ (getPracticeArea() == null ? 0 : this.getPracticeArea()
						.hashCode());
		return result;
	}

}
