package com.lawyer.entity;

// Generated Aug 7, 2013 11:09:49 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ReviewId generated by hbm2java
 */
@Embeddable
public class ReviewId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int userId;
	private int lawyerId;
	private int documentId;

	public ReviewId() {
	}

	public ReviewId(int userId, int lawyerId, int documentId) {
		this.userId = userId;
		this.lawyerId = lawyerId;
		this.documentId = documentId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "lawyer_id", nullable = false)
	public int getLawyerId() {
		return this.lawyerId;
	}

	public void setLawyerId(int lawyerId) {
		this.lawyerId = lawyerId;
	}

	@Column(name = "document_id", nullable = false)
	public int getDocumentId() {
		return this.documentId;
	}

	public void setDocumentId(int documentId) {
		this.documentId = documentId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReviewId))
			return false;
		ReviewId castOther = (ReviewId) other;

		return (this.getUserId() == castOther.getUserId())
				&& (this.getLawyerId() == castOther.getLawyerId())
				&& (this.getDocumentId() == castOther.getDocumentId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getLawyerId();
		result = 37 * result + this.getDocumentId();
		return result;
	}

}
