package com.lawyer.entity;

// Generated Aug 7, 2013 11:09:49 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ServiceFeesId generated by hbm2java
 */
@Embeddable
public class ServiceFeesId implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private int lawyerId;
	private String service;

	public ServiceFeesId() {
	}

	public ServiceFeesId(int lawyerId, String service) {
		this.lawyerId = lawyerId;
		this.service = service;
	}

	@Column(name = "lawyer_id", nullable = false)
	public int getLawyerId() {
		return this.lawyerId;
	}

	public void setLawyerId(int lawyerId) {
		this.lawyerId = lawyerId;
	}

	@Column(name = "service", nullable = false, length = 20)
	public String getService() {
		return this.service;
	}

	public void setService(String service) {
		this.service = service;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ServiceFeesId))
			return false;
		ServiceFeesId castOther = (ServiceFeesId) other;

		return (this.getLawyerId() == castOther.getLawyerId())
				&& ((this.getService() == castOther.getService()) || (this
						.getService() != null && castOther.getService() != null && this
						.getService().equals(castOther.getService())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getLawyerId();
		result = 37 * result
				+ (getService() == null ? 0 : this.getService().hashCode());
		return result;
	}

}
